[linkvault_servers]
linkvault-vm ansible_host=34.171.112.14 ansible_user=vaultstudiohub ansible_ssh_private_key_file=~/.ssh/id_ed25519

[linkvault_servers:vars]
ansible_python_interpreter=/usr/bin/python3
